# Generated by Django 5.2 on 2025-04-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notification_time',
            field=models.IntegerField(choices=[(10, '10 minutes before'), (60, '1 hour before'), (1440, '1 day before')], default=60),
        ),
    ]
