# Generated by Django 5.0.14 on 2025-05-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_task_notification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manually_archived',
            field=models.BooleanField(default=False),
        ),
    ]
