# Generated by Django 5.0.14 on 2025-05-04 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_task_manually_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='manually_archived',
            new_name='ignore_archive',
        ),
    ]
