# Generated by Django 5.0.14 on 2025-04-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_task_is_archived_webpushsubscription_and_more'),
        ('todoapp', '0006_webpushsubscription_task_is_archived_and_more'),
    ]

    operations = [
    ]
