"""
Django settings for team1project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q=++kk4$-w%48$_pbtr^v0_b8i4f*8)-!1gz##im&s16fdx0pe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'editor-jhayescs4300-5.devedu.io', 
    'app-jhayescs4300-5.devedu.io', 
    'editor-samallenonline-5.devedu.io', 
    'app-samallenonline-5.devedu.io',
    'localhost',
    'todolist.mooo.com',
    'todolistapp.tech'
    ]

# Add your domain here if you are getting csrf verification error
CSRF_TRUSTED_ORIGINS = [
    'https://app-jhayescs4300-5.devedu.io',
    'https://app-samallenonline-5.devedu.io'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_select2',
    'todoapp',
    'webpush',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'team1project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'todoapp.context_processors.vapid_key',
            ],
        },
    },
]

WSGI_APPLICATION = 'team1project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'MST'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Make sure this line is included for app-specific static folders
STATICFILES_DIRS = [
    BASE_DIR / "todoapp/static",
]
# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BBiZBGqqJD6mKor9xOGrGh08LRpzaKyg4l0JspaEU6SewYJr3AkbHwSsIibZPT7ONhfQTJVNYTy90WCY0TZHjZ4=",
    "VAPID_PRIVATE_KEY": "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgYUfUxUOC1z6aYUqLm4T_OUJ9Hz4KtoVNo5Edx2hsDYmhRANCAAQYmQRqqiQ-piqK_cThqxodPC0ac2isoOJdCbKWhFOknsGCa9wJGx8ErCIm2T0-zjYX0EyVTWE8vdFgmNE2R42e",
    "VAPID_ADMIN_EMAIL": "mailto:team1todo@gmail.com",
}

VAPID_PUBLIC_KEY = "BBiZBGqqJD6mKor9xOGrGh08LRpzaKyg4l0JspaEU6SewYJr3AkbHwSsIibZPT7ONhfQTJVNYTy90WCY0TZHjZ4="

EMAIL_HOST_USER = 'team1todo@gmail.com'
EMAIL_HOST_PASSWORD = 'nurp publ jksb bbda'
DEFAULT_FROM_EMAIL = 'team1todo@gmail.com'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SELECT2_CACHE_BACKEND = 'default'
SELECT2_CACHE_BACKEND_ALIAS = 'select2'

# Used for task suggestions OPENAI API implementation 
load_dotenv()
OPENAI_TASK_SUGGESTION = os.getenv("OPENAI_TASK_SUGGESTION")