name: To-Do App CI Pipeline

on:
  push:
    branches:
      - main
      - dev-branch
  pull_request:
    branches:
      - main
      - dev-branch

jobs:
  open_ai_code_review:
    name: OpenAI Code Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install Dependencies 
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      
      # Currently debugging with the help of ChatGPT
      - name: Run OpenAI Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p openai-code-reviews
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")

          PR_TITLE=$(jq -r '.pull_request.title' $GITHUB_EVENT_PATH)
          PR_AUTHOR=$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)
          PR_URL=$(jq -r '.pull_request.html_url' $GITHUB_EVENT_PATH)

          git fetch origin ${{ github.base_ref }} ${{ github.head_ref }}
          git diff origin/${{ github.base_ref }}..origin/${{ github.head_ref }} > pr_diff.txt

          if [ ! -s pr_diff.txt ]; then
            echo "Error: No changes detected. Skipping AI review." > openai-code-reviews/review_${TIMESTAMP}.txt
            exit 0
          fi

          PR_DIFF=$(head -c 4000 pr_diff.txt)

          cat <<EOF > request.json
          {
            "model": "gpt-4",
            "messages": [
              {"role": "system", "content": "You are an expert software reviewer. Provide detailed, constructive feedback."},
              {"role": "user", "content": "## PR Details\n**Title:** $PR_TITLE\n**Author:** $PR_AUTHOR\n**URL:** $PR_URL"},
              {"role": "user", "content": "## Code Changes\n\n\`\`\`diff\n$PR_DIFF\n\`\`\`"},
              {"role": "user", "content": "### Evaluate:\n1. **Code Quality**\n2. **Security Risks**\n3. **Best Practices**\n4. **Performance**\n5. **General Comments**"}
            ]
          }
          EOF

          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @request.json)

          echo "$RESPONSE" > openai-api-response.json

          jq -r '.choices[0].message.content // "Error: OpenAI response is empty or malformed."' openai-api-response.json > openai-code-reviews/review_${TIMESTAMP}.txt

      - name: Debug OpenAI API Response
        run: cat openai-api-response.json

      - name: Upload AI Code Review
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-code-review
          path: openai-code-reviews/*.txt

  tests:
    name: Run Django Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          source venv/bin/activate
          mkdir -p test_results
          cd team1project
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          python manage.py test | tee ../test_results/test_results_${TIMESTAMP}.txt || echo "No tests found, skipping test step."

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_results/*.txt

  coverage:
    name: Report Test Coverage
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Generate Coverage Report
        run: |
          source venv/bin/activate
          mkdir -p coverage_reports
          cd team1project
          coverage run --source='.' manage.py test
          coverage report -m
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          coverage xml -o ../coverage_reports/coverage_${TIMESTAMP}.xml

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_reports/*.xml
