name: To-Do App CI Pipeline

on:
  push:
    branches:
      - main
      - dev-branch
  pull_request:
    branches:
      - main
      - dev-branch

jobs:
  open_ai_code_review:
    name: OpenAI Code Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install Dependencies 
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run OpenAI Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p openai-code-reviews
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")

          PR_TITLE=$(jq -r '.pull_request.title' $GITHUB_EVENT_PATH)
          PR_AUTHOR=$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)
          PR_URL=$(jq -r '.pull_request.html_url' $GITHUB_EVENT_PATH)
          
          git fetch origin ${{ github.base_ref }} ${{ github.head_ref }}
          git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }} > pr_diff.txt

          echo '{
            "model": "gpt-4",
            "messages": [{"role": "system", "content": "You are reviewing code changes. Please be professional and informative."},
                        {"role": "user", "content": "Review the code changes in this pull request for quality, security, and best practices. Please include general information about the pull request such as date, time, and messages. The review will be saved as a text file"},
                        {"role": "user", "content": "## Pull Request Details\nTitle: '"$PR_TITLE"'\nAuthor: '"$PR_AUTHOR"'\nURL: '"$PR_URL"'"},
                        {"role": "user", "content": "## Code Changes\n\n'"$(cat pr_diff.txt)"'"}]
            }' > request.json

          curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @request.json | jq -r '.choices[0].message.content' > openai-code-reviews/review_${TIMESTAMP}.txt

      - name: Upload AI Code Review
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-code-review
          path: openai-code-reviews/*.txt

  tests:
    name: Run Django Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          source venv/bin/activate
          mkdir -p test_results
          cd team1project
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          python manage.py test | tee ../test_results/test_results_${TIMESTAMP}.txt || echo "No tests found, skipping test step."

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_results/*.txt

  coverage:
    name: Report Test Coverage
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Generate Coverage Report
        run: |
          source venv/bin/activate
          mkdir -p coverage_reports
          cd team1project
          coverage run --source='.' manage.py test
          coverage report -m
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          coverage xml -o ../coverage_reports/coverage_${TIMESTAMP}.xml

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_reports/*.xml
